spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tasks_t1}
    username: ${SPRING_DATASOURCE_USERNAME:bank}
    password: ${SPRING_DATASOURCE_PASSWORD:bankpass}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: credit-processing-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

app:
  kafka:
    topics:
      credit-products: client.credit.products.command
      credit-decision: client.credit.decision.event
      payment-schedule: client.payment.schedule.event

  credit:
    max-limit: 5000000

server:
  port: 8083
